# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Custom MCP-specific checks using system node
  - repo: local
    hooks:
      - id: mcp-stdout-pollution-check
        name: MCP Stdout Pollution Check
        entry: node scripts/check-stdout-pollution.mjs
        language: system
        files: \.ts$
        pass_filenames: false

      - id: typescript-compile
        name: TypeScript Compilation Check
        entry: npx tsc --noEmit
        language: system
        files: \.ts$
        pass_filenames: false

default_stages: [pre-commit]
fail_fast: false
